name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Add repo to PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Lint
        run: ruff check .

      - name: Run tests
        env:
          AZURE_OPENAI_ENDPOINT: "https://example.com"
          AZURE_OPENAI_API_KEY: "test-key"
          AZURE_OPENAI_DEPLOYMENT: "dummy"
          AZURE_OPENAI_API_VERSION: "2024-05-01-preview"
        run: pytest -q
